(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#canvas'),ctx=canvas.getContext('2d',{alpha:false}),game=$('#game');let W=1,H=1,dpr=1,groundH=88,last=0,raf=0;
let installPrompt=null;
const screens=$$('.screen'),hud=$('#hud'),nav=$('#homeNav');
const SETTINGS_KEY='flappySettingsV2',DATA_KEY='flappyProgressV2';
const defaults={sound:true,music:true,haptics:true,shake:true,reducedMotion:false,contrast:false,volume:65,skin:'classic',trail:'white',pipe:'classic',world:'meadow',godMode:false};
const blank={games:0,best:0,totalScore:0,pipes:0,flaps:0,perfects:0,coins:0,bestCombo:0,streak:0,lastCompleted:'',dailyBest:{},dailyChallenges:{date:'',pipes:0,perfects:0,coins:0,rewarded:[]},perMode:{},unlocked:['classic','white','meadow']};
let settings=load(SETTINGS_KEY,defaults),data=load(DATA_KEY,blank);settings={...defaults,...settings};data={...blank,...data};
if(!localStorage.getItem(DATA_KEY)){try{const old=JSON.parse(localStorage.getItem('flappyAnalytics')||'null');if(old){data.games=+old.gamesPlayed||0;data.best=+old.bestScore||+localStorage.getItem('flappyHighScore')||0;data.totalScore=+old.totalScore||0;data.pipes=+old.totalPipes||0;data.flaps=+old.totalFlaps||0;data.streak=+old.streak||0;data.lastCompleted=old.lastPlayDate?new Date(old.lastPlayDate).toISOString().slice(0,10):''}}catch{}}
data.unlocked=[...new Set(['classic','white','meadow',...(data.unlocked||[])])];
const modeMeta={overall:{label:'Overall',desc:'Combined results from all ranked modes. Practice runs are kept separate.'},classic:{label:'Classic',desc:'The standard Flappy experience with gradually increasing difficulty.'},daily:{label:'Daily',desc:'A fixed, seeded course shared by every attempt on the same calendar day.'},rush:{label:'Rush',desc:'A faster course with tighter timing and double-value flight coins.'},hardcore:{label:'Hardcore',desc:'Narrow gaps, high speed, and triple-value flight coins.'},practice:{label:'Practice',desc:'A slower training course with wider gaps and visible collision bounds. Unranked.'}};
const modeStatBlank=()=>({games:0,best:0,totalScore:0,pipes:0,flaps:0,perfects:0,coins:0,bestCombo:0});
function ensureModeData(){if(!data.perMode||typeof data.perMode!=='object')data.perMode={};const hadModes=Object.keys(data.perMode).length>0;if(!hadModes)data.perMode.classic={games:data.games||0,best:data.best||0,totalScore:data.totalScore||0,pipes:data.pipes||0,flaps:data.flaps||0,perfects:data.perfects||0,coins:0,bestCombo:data.bestCombo||0};Object.keys(modeMeta).filter(k=>k!=='overall').forEach(k=>data.perMode[k]={...modeStatBlank(),...(data.perMode[k]||{})})}
ensureModeData();
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||structuredClone(f)}catch{return {...f}}}function save(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));localStorage.setItem(DATA_KEY,JSON.stringify(data))}
const img={};['bird-up.png','bird-mid.png','bird-down.png','bird-berry-up.png','bird-berry-mid.png','bird-berry-down.png','bird-aqua-up.png','bird-aqua-mid.png','bird-aqua-down.png','bird-ember-up.png','bird-ember-mid.png','bird-ember-down.png'].forEach(n=>{img[n]=new Image;img[n].src=n});
const skins=[{id:'classic',name:'Classic',file:'bird-mid.png',need:0},{id:'berry',name:'Berry',file:'bird-berry-mid.png',need:40},{id:'aqua',name:'Aqua',file:'bird-aqua-mid.png',need:100},{id:'ember',name:'Ember',file:'bird-ember-mid.png',need:200}];
const trails=[{id:'white',name:'Feathers',icon:'feather',color:'#8b7346',need:0},{id:'gold',name:'Golden',icon:'sparkles',color:'#e9a915',need:60},{id:'rainbow',name:'Rainbow',icon:'rainbow',color:'#a04fcd',need:160}];
const pipeStyles=[{id:'classic',name:'Classic',colors:['#173f0b','#91d52e','#327913'],need:0},{id:'pipe-ocean',name:'Ocean',colors:['#092846','#25a9d6','#0d527b'],need:75},{id:'pipe-candy',name:'Candy',colors:['#5b245f','#f06aa6','#8c3477'],need:140},{id:'pipe-gold',name:'Golden',colors:['#5b3b08','#ffd34d','#a66b0d'],need:220}];
const worlds=[{id:'meadow',name:'Meadow',icon:'meadow',color:'#4aa63a',need:0},{id:'sunset',name:'Sunset',icon:'sunset',color:'#e46c4c',need:80},{id:'midnight',name:'Midnight',icon:'moon',color:'#506bb7',need:250}];
const svg=(name,cls='svg-icon')=>`<svg class="${cls}" aria-hidden="true"><use href="#${name}"/></svg>`;
const achievements=[
 {id:'first',title:'First Flight',desc:'Complete one recorded run',test:d=>d.games>=1,goal:1,val:d=>d.games,reward:'Berry bird',rewardId:'berry'},
 {id:'perfect10',title:'Center Stage',desc:'Make 10 perfect passes',test:d=>d.perfects>=10,goal:10,val:d=>d.perfects,reward:'Precision bragging rights'},
 {id:'score25',title:'Sharp Shooter',desc:'Score 25 in one run',test:d=>d.best>=25,goal:25,val:d=>d.best,reward:'Sunset world',rewardId:'sunset'},
 {id:'pipes100',title:'Pipe Master',desc:'Pass 100 pipes',test:d=>d.pipes>=100,goal:100,val:d=>d.pipes,reward:'Aqua bird',rewardId:'aqua'},
 {id:'combo8',title:'In the Zone',desc:'Reach an 8× perfect combo',test:d=>d.bestCombo>=8,goal:8,val:d=>d.bestCombo,reward:'Golden trail',rewardId:'gold'},
 {id:'score50',title:'Flappy Legend',desc:'Score 50 in one run',test:d=>d.best>=50,goal:50,val:d=>d.best,reward:'Rainbow trail',rewardId:'rainbow'},
 {id:'streak7',title:'Unstoppable',desc:'Build a 7-day streak',test:d=>d.streak>=7,goal:7,val:d=>d.streak,reward:'Midnight world',rewardId:'midnight'}];
const dailyChallengeDefs=[{id:'pipes',title:'Pipe Route',desc:'Pass 15 pipes today',goal:15,reward:20},{id:'perfects',title:'Perfect Form',desc:'Make 5 perfect passes today',goal:5,reward:25},{id:'coins',title:'Treasure Flight',desc:'Collect 5 flight coins today',goal:5,reward:30}];
let state='menu',mode='classic',returnScreen='menu',score=0,passed=0,runCoins=0,runFlaps=0,perfects=0,combo=0,bestCombo=0,elapsed=0,spawnClock=0,tier=0,shake=0,flash=0,toastTimer=0,nearTimer=0,dailyRng=Math.random;
const bird={x:0,y:0,w:58,h:50,vy:0,rot:0,frame:'bird-mid.png',dead:false};let pipes=[],particles=[],clouds=[],collectibles=[];
function today(){return new Date().toISOString().slice(0,10)}function seeded(seed){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function show(id){screens.forEach(s=>s.classList.toggle('visible',s.id===id));nav.classList.toggle('hidden',id!=='menu');hud.classList.toggle('hidden',!['playing','paused'].includes(state));}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,1.7);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);groundH=Math.max(78,Math.min(108,H*.105));if(state==='menu'){bird.x=W*.27;bird.y=H*.44}makeClouds()}addEventListener('resize',resize);
function makeClouds(){if(clouds.length)return;for(let i=0;i<7;i++)clouds.push({x:Math.random()*W,y:35+Math.random()*H*.48,s:.5+Math.random(),layer:i%3})}
function tierStats(){const t=Math.min(6,Math.floor(passed/8));if(mode==='rush')return{tier:t,speed:220+t*20,gap:158-Math.min(28,t*5),every:Math.max(.88,1.12-t*.04)};if(mode==='hardcore')return{tier:t,speed:205+t*18,gap:132-Math.min(18,t*3),every:Math.max(.96,1.25-t*.045)};const practice=mode==='practice'?.76:1;return{tier:t,speed:(165+t*16)*practice,gap:(172-Math.min(38,t*7))+(mode==='practice'?28:0),every:Math.max(1.12,1.5-t*.055)/practice}}
function resetRun(){score=passed=runCoins=runFlaps=perfects=combo=bestCombo=0;elapsed=spawnClock=tier=shake=flash=toastTimer=nearTimer=0;pipes=[];particles=[];collectibles=[];bird.x=W*.28;bird.y=H*.43;bird.vy=0;bird.rot=0;bird.dead=false;dailyRng=mode==='daily'?seeded(today()):Math.random;$('#score').textContent='0';$('#coinHud b').textContent='0';$('#comboHud').classList.add('hidden');$('#modeBadge').textContent=mode.toUpperCase()+(settings.godMode?' · GOD':'')}
function start(m=mode){mode=m;state='playing';resetRun();show('none');hud.classList.remove('hidden');nav.classList.add('hidden');unlockAudio();flap();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function pause(){if(state!=='playing')return;state='paused';show('pause');stopMusic()}function resume(){if(state!=='paused')return;state='playing';show('none');hud.classList.remove('hidden');if(settings.music)startMusic();last=performance.now();raf=requestAnimationFrame(loop)}
function home(){state='menu';show('menu');stopMusic();renderHome();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function flap(){if(state!=='playing'||bird.dead)return;bird.vy=mode==='practice'?-425:-465;runFlaps++;tone(610,.045,'square',.035);buzz(10);burst(bird.x-19,bird.y+8,4,trailColor(),80)}
function spawnPipe(){const s=tierStats(),r=dailyRng(),margin=58,max=H-groundH-s.gap-75;const top=margin+r*Math.max(1,max-margin);const moving=s.tier>=2&&dailyRng()<Math.min(.35,s.tier*.06);pipes.push({x:W+30,top,base:top,bottom:top+s.gap,gap:s.gap,passed:false,moving,phase:dailyRng()*6.28,amp:18+dailyRng()*17});if(dailyRng()<.38)collectibles.push({x:W+62,y:top+s.gap/2+(dailyRng()-.5)*s.gap*.36,taken:false,pulse:dailyRng()*6})}
function passPipe(p){passed++;let center=p.top+p.gap/2,delta=Math.abs(bird.y-center),perfect=delta<Math.min(22,p.gap*.15);if(perfect){combo++;perfects++;bestCombo=Math.max(bestCombo,combo);let bonus=Math.min(3,Math.floor(combo/3));score+=1+bonus;burst(bird.x,bird.y,16,'#ffe45b',210);showTimed('#comboHud',900);$('#comboHud span').textContent=combo;chime()}else{combo=0;score++;$('#comboHud').classList.add('hidden');tone(880,.07,'square',.06)}$('#score').textContent=score;if(Math.floor(passed/8)>tier){tier=Math.floor(passed/8);$('#tierToast').textContent=tier===2?'MOVING PIPES!':'SPEED UP!';showTimed('#tierToast',1100)} }
function nearMiss(p){if(p.near)return;const horizontal=Math.abs((p.x+32)-bird.x)<38,edge=Math.min(Math.abs((bird.y-17)-p.top),Math.abs((bird.y+17)-p.bottom));if(horizontal&&edge<11&&edge>0){p.near=true;nearTimer=.7;$('#nearMiss').classList.remove('hidden');tone(340,.05,'sawtooth',.025);if(settings.shake&&!settings.reducedMotion)shake=3}}
function collide(p){let l=bird.x-19,r=bird.x+19,t=bird.y-17,b=bird.y+17;return r>p.x&&l<p.x+64&&(t<p.top||b>p.bottom)}
function die(){if(bird.dead)return;bird.dead=true;bird.vy=-270;combo=0;shake=settings.shake&&!settings.reducedMotion?13:0;flash=settings.reducedMotion?0:.24;tone(110,.24,'sawtooth',.1);buzz([30,25,55]);burst(bird.x,bird.y,24,'#fff0cf',280)}
function finish(){state='gameover';stopMusic();const recorded=mode!=='practice';let isBest=false;recordModeRun();if(recorded){data.games++;data.totalScore+=score;data.pipes+=passed;data.flaps+=runFlaps;data.perfects+=perfects;data.coins+=runCoins;data.bestCombo=Math.max(data.bestCombo,bestCombo);if(score>data.best){data.best=score;isBest=true}if(mode==='daily')data.dailyBest[today()]=Math.max(data.dailyBest[today()]||0,score);applyDailyProgress();completeDay();unlockEarned()}save();$('#finalScore').textContent=score;$('#bestScore').textContent=data.best;$('#perfectResult').textContent=perfects;$('#comboResult').textContent=bestCombo;$('#coinsResult').textContent=runCoins;$('#newBest').classList.toggle('hidden',!isBest);$('#nextUnlockResult').textContent=nextUnlock();show('gameover');hud.classList.add('hidden')}
function completeDay(){const now=today();if(data.lastCompleted===now)return;let d=new Date;d.setDate(d.getDate()-1);data.streak=data.lastCompleted===d.toISOString().slice(0,10)?data.streak+1:1;data.lastCompleted=now}
function recordModeRun(){ensureModeData();const m=data.perMode[mode]||(data.perMode[mode]=modeStatBlank());m.games++;m.totalScore+=score;m.pipes+=passed;m.flaps+=runFlaps;m.perfects+=perfects;m.coins+=runCoins;m.best=Math.max(m.best,score);m.bestCombo=Math.max(m.bestCombo,bestCombo)}
function ensureDaily(){if(!data.dailyChallenges||data.dailyChallenges.date!==today())data.dailyChallenges={date:today(),pipes:0,perfects:0,coins:0,rewarded:[]};if(!Array.isArray(data.dailyChallenges.rewarded))data.dailyChallenges.rewarded=[]}
function applyDailyProgress(){ensureDaily();const d=data.dailyChallenges;d.pipes+=passed;d.perfects+=perfects;d.coins+=runCoins;dailyChallengeDefs.forEach(c=>{if(d[c.id]>=c.goal&&!d.rewarded.includes(c.id)){d.rewarded.push(c.id);data.coins+=c.reward}})}
function unlockEarned(){[...skins,...trails,...pipeStyles,...worlds].forEach(x=>{if(data.coins>=x.need&&!data.unlocked.includes(x.id))data.unlocked.push(x.id)});achievements.forEach(a=>{if(a.rewardId&&a.test(data)&&!data.unlocked.includes(a.rewardId))data.unlocked.push(a.rewardId)})}function nextUnlock(){const x=[...skins,...trails,...pipeStyles,...worlds].filter(x=>!data.unlocked.includes(x.id)).sort((a,b)=>a.need-b.need)[0];return x?`${Math.max(0,x.need-data.coins)} coins`:'ALL'}
function update(dt){elapsed+=dt;clouds.forEach(c=>{c.x-=(10+c.layer*14)*dt;if(c.x<-150)c.x=W+100});if(state==='menu')return;if(state!=='playing')return;if(bird.dead){bird.vy+=1550*dt;bird.y+=bird.vy*dt;bird.rot+=7*dt;if(bird.y>=H-groundH-24){bird.y=H-groundH-24;finish()}updateFx(dt);return}bird.vy+=1450*dt;bird.y+=bird.vy*dt;bird.rot=Math.max(-.5,Math.min(1.15,bird.vy/650));bird.frame=bird.vy<-140?'bird-up.png':bird.vy>170?'bird-down.png':'bird-mid.png';spawnClock+=dt;const ts=tierStats();if(spawnClock>ts.every){spawnClock-=ts.every;spawnPipe()}for(let i=pipes.length-1;i>=0;i--){let p=pipes[i];p.x-=ts.speed*dt;if(p.moving){p.top=p.base+Math.sin(elapsed*1.55+p.phase)*p.amp;p.bottom=p.top+p.gap}if(!p.passed&&p.x+64<bird.x){p.passed=true;passPipe(p)}nearMiss(p);if(collide(p)&&!settings.godMode){die();break}if(p.x<-100)pipes.splice(i,1)}for(let i=collectibles.length-1;i>=0;i--){let c=collectibles[i];c.x-=ts.speed*dt;c.pulse+=dt*5;if(!c.taken&&Math.hypot(c.x-bird.x,c.y-bird.y)<30){c.taken=true;runCoins+=mode==='hardcore'?3:mode==='rush'?2:1;$('#coinHud b').textContent=runCoins;burst(c.x,c.y,12,'#ffd43b',170);chime()}if(c.x<-30||c.taken)collectibles.splice(i,1)}if(bird.y-17<0||bird.y+17>H-groundH){if(settings.godMode){bird.y=Math.max(18,Math.min(H-groundH-18,bird.y));bird.vy=0}else die()}updateFx(dt)}
function updateFx(dt){particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt});particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-35*dt);flash=Math.max(0,flash-dt);nearTimer=Math.max(0,nearTimer-dt);if(!nearTimer)$('#nearMiss').classList.add('hidden')}
function loop(n){let dt=Math.min(.034,(n-last)/1000||0);last=n;update(dt);draw();if(state==='playing'||state==='menu')raf=requestAnimationFrame(loop)}
function skyColors(){let cycle=mode==='practice'?.18:(elapsed%90)/90;if(settings.world==='sunset')cycle=.48;if(settings.world==='midnight')cycle=.78;const stops=cycle<.38?['#39a9db','#bfe9e0']:cycle<.65?['#ef7e62','#ffd37c']:['#081b43','#284e7a'];return stops}
function draw(){let off=settings.shake&&!settings.reducedMotion?shake:0;ctx.save();ctx.translate((Math.random()-.5)*off,(Math.random()-.5)*off);drawWorld();pipes.forEach(drawPipe);collectibles.forEach(drawCoin);drawGround();if(state!=='menu')drawBird();drawParticles();ctx.restore();$('#flash').style.opacity=flash?String(flash*2.8):'0'}
function drawWorld(){const [a,b]=skyColors(),g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let night=a==='#081b43';if(night){ctx.fillStyle='#fff7ad';for(let i=0;i<28;i++)ctx.fillRect((i*83)%W,(i*47)%(H*.55),2,2);ctx.beginPath();ctx.arc(W*.82,90,30,0,7);ctx.fill()}drawLayer(H-groundH-105,38,'rgba(34,91,119,.28)',.25);drawLayer(H-groundH-65,62,'rgba(28,111,84,.48)',.55);clouds.forEach(c=>{ctx.globalAlpha=.32+c.layer*.17;ctx.fillStyle='#fff';let s=16*c.s;ctx.fillRect(c.x,c.y,s*5,s);ctx.fillRect(c.x+s,c.y-s,s*2,s);ctx.fillRect(c.x+s*2,c.y-s*1.6,s*2,s*1.6)});ctx.globalAlpha=1}
function drawLayer(base,amp,color,scale){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H-groundH);for(let x=0;x<=W+30;x+=30)ctx.lineTo(x,base-Math.sin((x+elapsed*20*scale)/90)*amp);ctx.lineTo(W,H-groundH);ctx.fill()}
function drawPipe(p){let colors=pipeStyles.find(x=>x.id===settings.pipe)?.colors||pipeStyles[0].colors;const body=(y,h)=>{let g=ctx.createLinearGradient(p.x,0,p.x+64,0);g.addColorStop(0,colors[0]);g.addColorStop(.42,colors[1]);g.addColorStop(1,colors[2]);ctx.fillStyle=g;ctx.fillRect(p.x,y,64,h);ctx.strokeStyle='#0b2634';ctx.lineWidth=3;ctx.strokeRect(p.x,y,64,h)};body(0,p.top-24);body(p.bottom+24,H-groundH-p.bottom-24);ctx.fillStyle=colors[1];ctx.strokeStyle='#0b2634';ctx.lineWidth=3;ctx.fillRect(p.x-7,p.top-25,78,25);ctx.strokeRect(p.x-7,p.top-25,78,25);ctx.fillRect(p.x-7,p.bottom,78,25);ctx.strokeRect(p.x-7,p.bottom,78,25)}
function drawGround(){const y=H-groundH;ctx.fillStyle='#7bc942';ctx.fillRect(0,y,W,12);ctx.fillStyle='#3f962d';for(let x=-20-(elapsed*70%28);x<W+28;x+=28){ctx.beginPath();ctx.moveTo(x,y+12);ctx.lineTo(x+14,y);ctx.lineTo(x+28,y);ctx.lineTo(x+14,y+12);ctx.fill()}ctx.fillStyle='#d9b96f';ctx.fillRect(0,y+12,W,groundH-12);ctx.fillStyle='rgba(128,83,35,.18)';for(let row=0;row<4;row++){const yy=y+25+row*17;for(let x=(row%2)*18;x<W;x+=48)ctx.fillRect(x,yy,24,2)}ctx.fillStyle='#9b7138';ctx.fillRect(0,y+12,W,3)}
function birdAsset(){return settings.skin==='classic'?bird.frame:bird.frame.replace('bird-',`bird-${settings.skin}-`)}
function drawBird(alpha=1,y=bird.y,rot=bird.rot){let im=img[birdAsset()]||img[bird.frame];if(!im?.complete)return;ctx.save();ctx.globalAlpha=alpha;ctx.translate(bird.x,y);ctx.rotate(rot);ctx.drawImage(im,-29,-25,58,50);if(mode==='practice'){ctx.strokeStyle='#ff3355';ctx.lineWidth=2;ctx.strokeRect(-19,-17,38,34)}ctx.restore()}
function drawCoin(c){ctx.save();ctx.translate(c.x,c.y);let s=1+Math.sin(c.pulse)*.1;ctx.scale(s,s);ctx.fillStyle='#ffd83d';ctx.strokeStyle='#5f3b08';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,12,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#fff19a';ctx.fillRect(-3,-7,4,9);ctx.restore()}
function trailColor(){return settings.trail==='gold'?'#ffd43b':settings.trail==='rainbow'?`hsl(${elapsed*180%360} 90% 65%)`:'#fff'}function burst(x,y,n,color,speed){if(settings.reducedMotion)n=Math.ceil(n/3);for(let i=0;i<n;i++){let a=Math.random()*6.28,v=Math.random()*speed;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.35+Math.random()*.35,max:.7,size:2+Math.random()*4,color})}}function drawParticles(){particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1}
let ac,musicTimer;function unlockAudio(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext);if(ac.state==='suspended')ac.resume();if(settings.music)startMusic()}function tone(freq,dur,type='square',gain=.04){if(!settings.sound||!ac)return;let o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain*settings.volume/100,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(ac.destination);o.start();o.stop(t+dur)}function chime(){tone(880,.08,'square',.05);setTimeout(()=>tone(1320,.1,'square',.04),70)}function startMusic(){stopMusic();if(!settings.music||!ac)return;let notes=[220,277,330,440,330,277],i=0;musicTimer=setInterval(()=>{let was=settings.sound;settings.sound=true;tone(notes[i++%notes.length],.14,'triangle',.018);settings.sound=was},260)}function stopMusic(){clearInterval(musicTimer)}function buzz(p){if(settings.haptics&&navigator.vibrate)navigator.vibrate(p)}
function showTimed(sel,ms){let e=$(sel);e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),ms)}
function renderHome(){ensureDaily();$('#streakValue').textContent=data.streak;$('#quickMusic span').textContent=settings.music?'ON':'OFF';$('#quickSound span').textContent=settings.sound?'ON':'OFF';$('#challengeSummary').textContent=dailyChallengeDefs.filter(c=>data.dailyChallenges[c.id]>=c.goal).length+'/3';game.classList.toggle('reduced-motion',settings.reducedMotion);game.classList.toggle('high-contrast',settings.contrast);renderSettings()}
function renderSettings(){[['soundToggle','sound'],['musicToggle','music'],['hapticsToggle','haptics'],['shakeToggle','shake'],['motionToggle','reducedMotion'],['contrastToggle','contrast']].forEach(([id,k])=>$('#'+id).checked=settings[k]);$('#volumeRange').value=settings.volume}
let statsView='overall';
function renderStats(view=statsView){ensureModeData();statsView=view;$('#statsTabs').innerHTML=Object.entries(modeMeta).map(([id,m])=>`<button class="stats-tab ${id===view?'active':''}" data-stats-mode="${id}">${m.label}</button>`).join('');const overall=view==='overall',s=overall?{games:data.games,best:data.best,totalScore:data.totalScore,pipes:data.pipes,flaps:data.flaps,perfects:data.perfects,coins:data.coins,bestCombo:data.bestCombo}:data.perMode[view];let detail=modeMeta[view].desc;if(view==='daily')detail+=` Today's best: ${data.dailyBest[today()]||0}.`;$('#statsModeInfo').innerHTML=`<b>${modeMeta[view].label}</b>${detail}`;let avg=s.games?(s.totalScore/s.games).toFixed(1):'0';$('#statsGrid').innerHTML=[['Best Score',s.best],['Runs',s.games],['Average Score',avg],['Pipes Passed',s.pipes],['Perfect Passes',s.perfects],['Best Combo',s.bestCombo+'×'],['Total Flaps',s.flaps],[overall?'Wallet Coins':'Coins Collected',s.coins]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function renderAchievements(){$('#achievementList').innerHTML=achievements.map(a=>{let v=Math.min(a.goal,a.val(data)),pct=Math.floor(v/a.goal*100),done=a.test(data);return`<article class="achievement ${done?'done':''}"><header><span>${svg(done?'check':'trophy','svg-icon status-icon')}${a.title}</span><b>${done?'DONE':pct+'%'}</b></header><small>${a.desc} · ${a.reward}</small><div class="progress"><i style="width:${pct}%"></i></div></article>`}).join('')}
function renderChallenges(){ensureDaily();const d=data.dailyChallenges;$('#challengeList').innerHTML=dailyChallengeDefs.map(c=>{let value=Math.min(c.goal,d[c.id]),pct=Math.floor(value/c.goal*100),done=value>=c.goal,rewarded=d.rewarded.includes(c.id);return`<article class="achievement ${done?'done':''}"><header><span>${svg(done?'check':'calendar','svg-icon status-icon')}${c.title}</span><b>${value}/${c.goal}</b></header><small>${c.desc} · <span class="${rewarded?'challenge-complete':'challenge-reward'}">${rewarded?'Reward collected':c.reward+' coins'}</span></small><div class="progress"><i style="width:${pct}%"></i></div></article>`}).join('')}
function renderWardrobe(){$('#walletValue').textContent=data.coins;[['skinGrid',skins,'skin'],['trailGrid',trails,'trail'],['pipeGrid',pipeStyles,'pipe'],['worldGrid',worlds,'world']].forEach(([id,arr,key])=>{$('#'+id).innerHTML=arr.map(x=>{let unlocked=data.unlocked.includes(x.id),preview;if(key==='skin')preview=`<img class="skin-preview" src="${x.file}" alt="${x.name} bird">`;else if(key==='pipe')preview=`<span class="pipe-preview" style="--p1:${x.colors[0]};--p2:${x.colors[1]};--p3:${x.colors[2]}"><i></i></span>`;else preview=svg(x.icon,'wardrobe-icon');return`<button class="choice ${unlocked?'':'locked'} ${settings[key]===x.id?'selected':''}" data-choice="${key}" data-id="${x.id}" ${unlocked?'':'disabled'}><span class="preview" style="color:${x.color||'inherit'}">${preview}</span><span class="choice-name">${x.name}</span>${unlocked?`<span class="choice-state">${settings[key]===x.id?svg('check','mini-state-icon'):''}</span>`:`<span class="choice-cost">${svg('lock','mini-state-icon')}${x.need} coins</span>`}</button>`}).join('')})}
function openPanel(id){returnScreen=state==='paused'?'pause':'menu';if(id==='stats')renderStats();if(id==='achievements')renderAchievements();if(id==='challenges')renderChallenges();if(id==='wardrobe')renderWardrobe();if(id==='settings')renderSettings();show(id)}function closePanel(){show(returnScreen);if(returnScreen==='pause')hud.classList.remove('hidden')}
$('#playBtn').onclick=()=>start('classic');$('#dailyBtn').onclick=()=>start('daily');$('#practiceBtn').onclick=()=>start('practice');$('#rushBtn').onclick=()=>start('rush');$('#hardcoreBtn').onclick=()=>start('hardcore');$('#challengesBtn').onclick=()=>openPanel('challenges');$('#restartBtn').onclick=()=>start(mode);$('#pauseBtn').onclick=pause;$('#resumeBtn').onclick=resume;$('#quitBtn').onclick=home;$('#homeBtn').onclick=home;
$$('[data-open]').forEach(b=>b.onclick=e=>openPanel(e.currentTarget.dataset.open));$$('[data-close]').forEach(b=>b.onclick=closePanel);
$('#quickMusic').onclick=()=>{settings.music=!settings.music;save();renderHome()};$('#quickSound').onclick=()=>{settings.sound=!settings.sound;save();renderHome()};
[['soundToggle','sound'],['musicToggle','music'],['hapticsToggle','haptics'],['shakeToggle','shake'],['motionToggle','reducedMotion'],['contrastToggle','contrast']].forEach(([id,k])=>$('#'+id).onchange=e=>{settings[k]=e.target.checked;if(k==='music'&&!settings.music)stopMusic();save();renderHome()});$('#volumeRange').oninput=e=>{settings.volume=+e.target.value;save()};
$('#wardrobe').onclick=e=>{let b=e.target.closest('[data-choice]');if(!b)return;settings[b.dataset.choice]=b.dataset.id;save();renderWardrobe()};
$('#statsTabs').onclick=e=>{const tab=e.target.closest('[data-stats-mode]');if(tab)renderStats(tab.dataset.statsMode)};
let cheatTaps=0,cheatTapTimer=0;
$('#settingsTitle').onclick=()=>{clearTimeout(cheatTapTimer);cheatTaps++;cheatTapTimer=setTimeout(()=>cheatTaps=0,1800);if(cheatTaps>=7){cheatTaps=0;$('#cheatPanel').classList.toggle('hidden');$('#cheatFeedback').className='cheat-feedback';$('#cheatFeedback').textContent='Enter a developer code.';if(!$('#cheatPanel').classList.contains('hidden'))$('#cheatInput').focus()}};
function applyCheat(){const code=$('#cheatInput').value.trim().toLowerCase(),feedback=$('#cheatFeedback');feedback.className='cheat-feedback';if(code==='doublecheeseburger'){settings.godMode=!settings.godMode;save();feedback.textContent=`God Mode ${settings.godMode?'enabled. Collisions are disabled.':'disabled. Collisions are active.'}`;feedback.classList.add('success');tone(980,.12,'square',.05)}else if(code==='quarterpounder'){data.coins+=100;unlockEarned();save();feedback.textContent='100 coins added to your wallet.';feedback.classList.add('success');tone(1180,.12,'square',.05)}else{feedback.textContent='Invalid developer code.';feedback.classList.add('error');tone(130,.18,'sawtooth',.05)}$('#cheatInput').value=''}
$('#cheatApply').onclick=applyCheat;$('#cheatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();applyCheat()}};
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')};
addEventListener('appinstalled',()=>{$('#installBtn').classList.add('hidden');installPrompt=null});
function gameplayPointer(e){if(state!=='playing')return;const target=e.target;if(target instanceof Element&&target.closest('button,input,label,a,[role="button"]'))return;if(e.cancelable)e.preventDefault();flap()}
if('PointerEvent' in window)document.addEventListener('pointerdown',gameplayPointer,{capture:true,passive:false});else document.addEventListener('touchstart',gameplayPointer,{capture:true,passive:false});
$('#gameover').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;start(mode)});
addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();if(state==='playing')flap();else if(state==='gameover')start(mode)}if(e.code==='KeyP'||e.code==='Escape'){if(state==='playing')pause();else if(state==='paused')resume()}});addEventListener('blur',()=>{if(state==='playing')pause()});
if('serviceWorker' in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
resize();unlockEarned();renderHome();show('menu');last=performance.now();raf=requestAnimationFrame(loop);
})();
